#ifndef OMID_H
#define OMID_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Bitmask for the touched state.
 */
#define OmidFlags_TOUCHED 1

/**
 * Bitmask for the raw data flag.
 */
#define OmidFlags_RAW_DATA 2

/**
 * Bitmask for the direction flag.
 */
#define OmidFlags_DIRECTION 4

/**
 * Total serialized size of the UACT frame in bytes.
 */
#define UactFrame_FRAME_SIZE ((C * 4) + 8)

/**
 * The type of action or transaction represented by an Omid control packet.
 */
enum EventType
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
  /**
   * Unrecognized or placeholder event.
   */
  Unknown = 0,
  /**
   * Absolute parameter change (e.g. fader move).
   */
  AbsoluteChange = 1,
  /**
   * Relative parameter adjustment (e.g. rotary encoder tick).
   */
  RelativeDelta = 2,
  /**
   * Key press event on a piano keyboard or pad.
   */
  KeyPress = 3,
  /**
   * Key release event on a piano keyboard or pad.
   */
  KeyRelease = 4,
  /**
   * Direct command/haptic vibration to the device's actuator.
   */
  HapticFeedback = 5,
  /**
   * Event to update local LEDs or displays on the controller.
   */
  VisualUpdate = 6,
  /**
   * Initial startup or clock sync handshake between host and controller.
   */
  SystemHandshake = 7,
};
#if __STDC_VERSION__ >= 202311L
typedef enum EventType EventType;
#else
typedef uint8_t EventType;
#endif // __STDC_VERSION__ >= 202311L

/**
 * A wrapper struct for the 8-bit packet configuration flags field.
 *
 * Layout:
 * - Bit 0: Touched flag (active touch sensor)
 * - Bit 1: Raw Data flag (specifies if payload is ADC/raw integer vs normalized f32)
 * - Bit 2: Direction flag (0 for positive, 1 for negative increment)
 * - Bits 3..7: Sub-sample microsecond timer delta offset (0..31 ticks)
 */
typedef struct OmidFlags OmidFlags;

/**
 * An 8-byte unified control & haptic packet for the OMID Protocol.
 *
 * Packets are designed to be extremely compact, predictable, and suitable for
 * lock-free routing and direct DMA hardware transfers.
 */
typedef struct OmidPacket {
  /**
   * The unique 16-bit identifier of the target control object (e.g. key index, fader number).
   */
  uint16_t object_id;
  /**
   * The raw byte value representing the type of event (mapped to `EventType`).
   */
  uint8_t event_type;
  /**
   * Configuration flags containing state flags (touched, raw data, direction) and the sub-sample timer delta.
   */
  uint8_t flags;
  /**
   * The 32-bit payload, which can represent floats, integers, xy coordinates, or ADC values.
   */
  uint32_t payload;
} OmidPacket;




/**
 * Spatial placement and resolution descriptor for OMID physical control objects.
 *
 * Sent during system handshakes to inform the host of a control's physical layout
 * and resolution properties for UI and haptic map rendering.
 */
typedef struct TopologyDescriptor {
  /**
   * The unique identifier of the target control object.
   */
  uint16_t object_id;
  /**
   * The classification of the control (e.g. 0x01 = Fader, 0x02 = Key, 0x03 = XY Pad).
   */
  uint8_t object_type;
  /**
   * Physical location offset on the horizontal X axis (in millimeters).
   */
  uint16_t spatial_x;
  /**
   * Physical location offset on the vertical Y axis (in millimeters).
   */
  uint16_t spatial_y;
  /**
   * The bit resolution of the sensor (e.g. 12 for 12-bit ADC, 16 for 16-bit ADC).
   */
  uint8_t resolution;
} TopologyDescriptor;

typedef uintptr_t libc_pthread_t;

typedef struct cpu_set_t {
  uintptr_t bits[16];
} cpu_set_t;

/**
 * Alias for relative delta changes.
 */
#define EventType_RelativeChange RelativeDelta

/**
 * Creates a new `OmidPacket` with raw fields.
 */
struct OmidPacket omid_packet_new(uint16_t object_id,
                                  uint8_t event_type,
                                  uint8_t flags,
                                  uint32_t payload);

/**
 * Creates a new `OmidPacket` carrying a 32-bit single-precision float.
 */
struct OmidPacket omid_packet_new_f32(uint16_t object_id,
                                      uint8_t event_type,
                                      uint8_t flags,
                                      float val);

/**
 * Creates a new `OmidPacket` carrying a 32-bit signed integer.
 */
struct OmidPacket omid_packet_new_i32(uint16_t object_id,
                                      uint8_t event_type,
                                      uint8_t flags,
                                      int32_t val);

/**
 * Creates a new `OmidPacket` carrying a 32-bit unsigned integer.
 */
struct OmidPacket omid_packet_new_u32(uint16_t object_id,
                                      uint8_t event_type,
                                      uint8_t flags,
                                      uint32_t val);

/**
 * Creates a new `OmidPacket` carrying two 16-bit coordinates (X and Y).
 */
struct OmidPacket omid_packet_new_xy(uint16_t object_id,
                                     uint8_t event_type,
                                     uint8_t flags,
                                     uint16_t x,
                                     uint16_t y);

/**
 * Creates a new `OmidPacket` representing haptic feedback.
 */
struct OmidPacket omid_packet_new_haptic(uint16_t object_id, uint8_t profile, float intensity);

/**
 * Creates a new `OmidPacket` carrying a 12-bit ADC value.
 */
struct OmidPacket omid_packet_new_adc12(uint16_t object_id,
                                        uint8_t event_type,
                                        uint8_t flags,
                                        uint16_t val);

/**
 * Creates a new `OmidPacket` carrying a 16-bit ADC value.
 */
struct OmidPacket omid_packet_new_adc16(uint16_t object_id,
                                        uint8_t event_type,
                                        uint8_t flags,
                                        uint16_t val);

/**
 * Deserializes a packet from a raw 8-byte array.
 *
 * # Safety
 *
 * The caller must ensure that the `bytes` pointer points to a valid, initialized block of at least 8 bytes
 * of memory and is safe to read.
 */
struct OmidPacket omid_packet_from_bytes(const uint8_t *bytes);

/**
 * Serializes a packet into a raw 8-byte buffer.
 *
 * # Safety
 *
 * The caller must ensure that the `out_bytes` pointer points to a valid, writable block of at least 8 bytes
 * of memory and is safe to write.
 */
void omid_packet_to_bytes(struct OmidPacket packet,
                          uint8_t *out_bytes);

/**
 * Extracts the payload as a 32-bit float.
 */
float omid_packet_payload_as_f32(struct OmidPacket packet);

/**
 * Extracts the payload as a 32-bit signed integer.
 */
int32_t omid_packet_payload_as_i32(struct OmidPacket packet);

/**
 * Extracts the payload as a 32-bit unsigned integer.
 */
uint32_t omid_packet_payload_as_u32(struct OmidPacket packet);

/**
 * Extracts the XY coordinate payload from a packet.
 *
 * # Safety
 *
 * The caller must ensure that `out_x` and `out_y` are either null or point to valid, writable
 * 16-bit memory locations.
 */
void omid_packet_payload_as_xy(struct OmidPacket packet, uint16_t *out_x, uint16_t *out_y);

/**
 * Extracts the 12-bit ADC value from the packet payload.
 */
uint16_t omid_packet_payload_as_adc12(struct OmidPacket packet);

/**
 * Extracts the 16-bit ADC value from the packet payload.
 */
uint16_t omid_packet_payload_as_adc16(struct OmidPacket packet);

/**
 * Normalizes raw ADC values based on resolution bits.
 */
float omid_packet_payload_as_normalized_f32(struct OmidPacket packet, uint8_t adc_bits);

/**
 * Returns the intensity payload for haptic events.
 */
float omid_packet_haptic_intensity(struct OmidPacket packet);

/**
 * Returns the force profile ID for haptic events, or -1 if invalid.
 */
int32_t omid_packet_haptic_force_profile(struct OmidPacket packet);

/**
 * Helper to construct a flags byte.
 */
uint8_t omid_flags_new(bool touched, bool raw_data, bool direction, uint8_t timer_delta);

/**
 * Helper to check the touched bit from raw flags.
 */
bool omid_flags_is_touched(uint8_t flags);

/**
 * Helper to check the raw data bit from raw flags.
 */
bool omid_flags_is_raw_data(uint8_t flags);

/**
 * Helper to check the direction bit from raw flags.
 */
bool omid_flags_direction(uint8_t flags);

/**
 * Helper to check the timer delta from raw flags.
 */
uint8_t omid_flags_timer_delta(uint8_t flags);

/**
 * Creates a new `TopologyDescriptor`.
 */
struct TopologyDescriptor omid_topology_new(uint16_t object_id,
                                            uint8_t object_type,
                                            uint16_t spatial_x,
                                            uint16_t spatial_y,
                                            uint8_t resolution);

/**
 * Deserializes a topology descriptor from a raw 8-byte array.
 *
 * # Safety
 *
 * The caller must ensure that the `bytes` pointer points to a valid, initialized block of at least 8 bytes
 * of memory and is safe to read.
 */
struct TopologyDescriptor omid_topology_from_bytes(const uint8_t *bytes);

/**
 * Serializes a topology descriptor into a raw 8-byte buffer.
 *
 * # Safety
 *
 * The caller must ensure that the `out_bytes` pointer points to a valid, writable block of at least 8 bytes
 * of memory and is safe to write.
 */
void omid_topology_to_bytes(struct TopologyDescriptor desc,
                            uint8_t *out_bytes);

extern libc_pthread_t pthread_self(void);

extern int pthread_setaffinity_np(libc_pthread_t thread,
                                  uintptr_t cpusetsize,
                                  const struct cpu_set_t *cpuset);

#endif  /* OMID_H */
